default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  template: template0

development:
  <<: *default
  database: food_development

test:
  <<: *default
  database: food_test

production:
  <<: *default
  database: food_production
  username: food
  password: <%= ENV['FOOD_DATABASE_PASSWORD'] %>
